# Generated by Django 5.2.4 on 2026-02-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_teacher_department_remove_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'exam', 'course')},
        ),
    ]
